"""
Python REPL Sandbox and Data Science Tool for Jarvis.
Allows autonomous code execution, numerical calculations, data manipulation,
and dynamic generation of Matplotlib/Plotly figures.
"""

import io
import sys
import math
import json
import logging
from typing import Dict, Any, List, Optional
from langchain_core.tools import tool

logger = logging.getLogger(__name__)

# Global or session-based figure buffer to allow Streamlit to display charts generated by agent
_FIGURE_BUFFER: List[Any] = []

def get_and_clear_figure_buffer() -> List[Any]:
    """Retrieve and clear captured figures for UI rendering."""
    global _FIGURE_BUFFER
    figs = list(_FIGURE_BUFFER)
    _FIGURE_BUFFER.clear()
    return figs

@tool
def python_interpreter(code: str) -> str:
    """
    Executes Python code in a sandboxed environment for mathematical calculations,
    data analysis with pandas/numpy, statistical modeling, and generating charts with matplotlib/plotly.
    Always use print() to output numbers, tables, or conclusions.
    
    Args:
        code: Valid Python code string to execute.
    """
    global _FIGURE_BUFFER
    # Clean code formatting if wrapped in markdown blocks
    clean_code = code.strip()
    if clean_code.startswith("```python"):
        clean_code = clean_code[9:]
    elif clean_code.startswith("```"):
        clean_code = clean_code[3:]
    if clean_code.endswith("```"):
        clean_code = clean_code[:-3]
    clean_code = clean_code.strip()

    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    old_stdout = sys.stdout
    old_stderr = sys.stderr

    # Pre-imported common scientific modules
    local_env: Dict[str, Any] = {
        "math": math,
        "json": json,
    }

    try:
        import numpy as np
        local_env["np"] = np
        local_env["numpy"] = np
    except ImportError:
        pass

    try:
        import pandas as pd
        local_env["pd"] = pd
        local_env["pandas"] = pd
    except ImportError:
        pass

    try:
        import matplotlib
        matplotlib.use("Agg")  # Non-interactive backend
        import matplotlib.pyplot as plt
        local_env["plt"] = plt
        local_env["matplotlib"] = matplotlib
    except ImportError:
        plt = None

    try:
        import plotly.express as px
        import plotly.graph_objects as go
        local_env["px"] = px
        local_env["go"] = go
    except ImportError:
        pass

    try:
        sys.stdout = stdout_capture
        sys.stderr = stderr_capture
        
        # Execute the code in isolated local namespace
        exec(clean_code, {}, local_env)

        # Check if a matplotlib plot was created
        if plt and len(plt.get_fignums()) > 0:
            for fig_num in plt.get_fignums():
                fig = plt.figure(fig_num)
                _FIGURE_BUFFER.append(fig)
            plt.close('all')

        stdout_val = stdout_capture.getvalue().strip()
        stderr_val = stderr_capture.getvalue().strip()

        result_parts = []
        if stdout_val:
            result_parts.append(f"[Output]:\n{stdout_val}")
        if stderr_val:
            result_parts.append(f"[Warnings/Stderr]:\n{stderr_val}")
        if not stdout_val and not stderr_val:
            result_parts.append("[Success: Code executed without textual output]")
        
        if _FIGURE_BUFFER:
            result_parts.append(f"[Chart Generated: {len(_FIGURE_BUFFER)} figure(s) rendered to user interface]")

        return "\n\n".join(result_parts)

    except Exception as e:
        logger.error(f"Python Execution Error: {str(e)}", exc_info=True)
        return f"Python Execution Error: {type(e).__name__}: {str(e)}"
    finally:
        sys.stdout = old_stdout
        sys.stderr = old_stderr
