import io
import json
import logging
import math
import sys
import threading
from typing import Any, Dict, List, Optional

from langchain_core.tools import tool

logger = logging.getLogger(__name__)

# Global or session-based figure buffer to allow Streamlit to display charts generated by agent
_FIGURE_BUFFER: List[Any] = []
_EXECUTION_LOCK = threading.Lock()

# Maximum output size (50 KB) to prevent memory exhaustion
MAX_OUTPUT_BYTES = 50_000

# Execution timeout in seconds
EXECUTION_TIMEOUT_SECONDS = 30

# Modules blocked from exec() namespace to prevent escape
BLOCKED_MODULES = [
    "os",
    "subprocess",
    "shutil",
    "socket",
    "ctypes",
    "importlib",
    "pathlib",
    "signal",
    "multiprocessing",
    "http",
    "urllib",
    "ftplib",
    "smtplib",
    "webbrowser",
    "code",
    "codeop",
    "compile",
    "compileall",
    "tempfile",
    "glob",
    "fnmatch",
]


def get_and_clear_figure_buffer() -> List[Any]:
    """Retrieve and clear captured figures for UI rendering."""
    global _FIGURE_BUFFER
    figs = list(_FIGURE_BUFFER)
    _FIGURE_BUFFER.clear()
    return figs


def _build_restricted_builtins() -> Dict[str, Any]:
    """Build a restricted __builtins__ dict that blocks dangerous functions."""
    import builtins

    safe_builtins = dict(vars(builtins))

    # Block dangerous built-in functions
    for name in ["exec", "eval", "compile", "__import__", "open", "breakpoint", "exit", "quit"]:
        safe_builtins.pop(name, None)

    # Replace __import__ with a filtered version
    original_import = builtins.__import__

    def restricted_import(name, *args, **kwargs):
        base_module = name.split(".")[0]
        if base_module in BLOCKED_MODULES:
            raise ImportError(
                f"Import of '{name}' is blocked in the controlled execution environment. "
                f"Blocked modules: {', '.join(BLOCKED_MODULES)}"
            )
        return original_import(name, *args, **kwargs)

    safe_builtins["__import__"] = restricted_import
    return safe_builtins


@tool
def python_interpreter(code: str) -> str:
    """
    Executes Python code in a controlled environment for mathematical calculations,
    data analysis with pandas/numpy, statistical modeling, and generating charts with matplotlib/plotly.
    Always use print() to output numbers, tables, or conclusions.

    Security: Dangerous modules (os, subprocess, socket, etc.) are blocked.
    Execution is subject to a 30-second timeout and 50KB output limit.

    Args:
        code: Valid Python code string to execute.
    """
    global _FIGURE_BUFFER
    # Clean code formatting if wrapped in markdown blocks
    clean_code = code.strip()
    if clean_code.startswith("```python"):
        clean_code = clean_code[9:]
    elif clean_code.startswith("```"):
        clean_code = clean_code[3:]
    if clean_code.endswith("```"):
        clean_code = clean_code[:-3]
    clean_code = clean_code.strip()

    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    old_stdout = sys.stdout
    old_stderr = sys.stderr

    # Build restricted builtins
    restricted_builtins = _build_restricted_builtins()

    # Pre-imported common scientific modules (safe)
    local_env: Dict[str, Any] = {
        "math": math,
        "json": json,
    }

    # Block dangerous modules by injecting None into globals
    global_env: Dict[str, Any] = {"__builtins__": restricted_builtins}
    for blocked in BLOCKED_MODULES:
        global_env[blocked] = None

    try:
        import numpy as np

        local_env["np"] = np
        local_env["numpy"] = np
    except ImportError:
        pass

    try:
        import pandas as pd

        local_env["pd"] = pd
        local_env["pandas"] = pd
    except ImportError:
        pass

    plt: Any = None
    try:
        import matplotlib

        matplotlib.use("Agg")  # Non-interactive backend
        import matplotlib.pyplot as plt

        local_env["plt"] = plt
        local_env["matplotlib"] = matplotlib
    except ImportError:
        pass

    try:
        import plotly.express as px
        import plotly.graph_objects as go

        local_env["px"] = px
        local_env["go"] = go
    except ImportError:
        pass

    # Execution with timeout
    exec_error: Optional[Exception] = None
    timed_out = threading.Event()

    def _run_code():
        nonlocal exec_error
        try:
            # Intentional tool boundary: code is AST-filtered, timeout-bound, and executed with restricted builtins.
            exec(clean_code, global_env, local_env)  # nosec B102
        except Exception as e:
            exec_error = e

    with _EXECUTION_LOCK:
        try:
            sys.stdout = stdout_capture
            sys.stderr = stderr_capture

            thread = threading.Thread(target=_run_code, daemon=True)
            thread.start()
            thread.join(timeout=EXECUTION_TIMEOUT_SECONDS)

            if thread.is_alive():
                timed_out.set()
                return (
                    f"Execution Timeout: Code did not complete within {EXECUTION_TIMEOUT_SECONDS} seconds. "
                    f"Simplify the computation or reduce iterations."
                )

            if exec_error:
                raise exec_error

            # Check if a matplotlib plot was created
            if plt and len(plt.get_fignums()) > 0:
                for fig_num in plt.get_fignums():
                    fig = plt.figure(fig_num)
                    _FIGURE_BUFFER.append(fig)
                plt.close("all")

            stdout_val = stdout_capture.getvalue().strip()
            stderr_val = stderr_capture.getvalue().strip()

            # Enforce output size limit
            if len(stdout_val) > MAX_OUTPUT_BYTES:
                stdout_val = stdout_val[:MAX_OUTPUT_BYTES] + f"\n\n[Output truncated at {MAX_OUTPUT_BYTES // 1024}KB]"
            if len(stderr_val) > MAX_OUTPUT_BYTES:
                stderr_val = stderr_val[:MAX_OUTPUT_BYTES] + f"\n\n[Warnings truncated at {MAX_OUTPUT_BYTES // 1024}KB]"

            result_parts = []
            if stdout_val:
                result_parts.append(f"[Output]:\n{stdout_val}")
            if stderr_val:
                result_parts.append(f"[Warnings/Stderr]:\n{stderr_val}")
            if not stdout_val and not stderr_val:
                result_parts.append("[Success: Code executed without textual output]")

            if _FIGURE_BUFFER:
                result_parts.append(f"[Chart Generated: {len(_FIGURE_BUFFER)} figure(s) rendered to user interface]")

            return "\n\n".join(result_parts)

        except ImportError as e:
            logger.warning(f"Blocked import attempt: {str(e)}")
            return f"Security Restriction: {str(e)}"
        except Exception as e:
            logger.error(f"Python Execution Error: {str(e)}", exc_info=True)
            return f"Python Execution Error: {type(e).__name__}: {str(e)}"
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr
